/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Product, Category, Address } from './types';

export const CATEGORIES: Category[] = [
  { id: 'all', name: 'All Fresh', icon: 'Sparkles' },
  { id: 'veggies', name: 'Fresh Produce', icon: 'Leaf' },
  { id: 'dairy', name: 'Dairy & Eggs', icon: 'Milk' },
  { id: 'meats', name: 'Meat & Seafood', icon: 'Beef' },
  { id: 'bakery', name: 'Bakery & Bread', icon: 'Croissant' },
  { id: 'beverages', name: 'Beverages', icon: 'Coffee' },
  { id: 'snacks', name: 'Snacks & Sweets', icon: 'Cookie' },
  { id: 'frozen', name: 'Frozen Food', icon: 'Sparkles' },
  { id: 'cleaning', name: 'Cleaning & Home', icon: 'Sparkles' },
];

export const PRODUCTS: Product[] = [
  // Fruits & Veggies
  {
    id: 'f1',
    name: 'Sri Lankan Organic Cavendish Bananas',
    description: 'Sweet, rich, and chemically-free grown local Cavendish bananas. Highly nutritious and perfect for daily energy boost.',
    category: 'fruits',
    price: 360,
    originalPrice: 450,
    discountPercent: 20,
    unit: '1 kg',
    image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 25,
    rating: 4.8,
    reviewsCount: 142,
  },
  {
    id: 'f2',
    name: 'Premium Red Seedless Grapes',
    description: 'Crisp, plump, and ultra-sweet red seedless grapes imported from elite vineyards. Hand-picked and thoroughly washed.',
    category: 'fruits',
    price: 1890,
    originalPrice: 2200,
    discountPercent: 14,
    unit: '500g pack',
    image: 'https://images.unsplash.com/photo-1601275868399-45bec4f4cd9d?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 12,
    rating: 4.9,
    reviewsCount: 88,
  },
  {
    id: 'f3',
    name: 'Fresh Colombo Local Papaya',
    description: 'Rich, orange-fleshed local papaya, harvested early this morning. Creamy texture and extremely sweet wellness aid.',
    category: 'fruits',
    price: 490,
    unit: '1.2 kg - 1.5 kg',
    image: 'https://images.unsplash.com/photo-1517282009859-f000ec3b26fe?w=500&auto=format&fit=crop&q=80',
    popular: false,
    stock: 18,
    rating: 4.6,
    reviewsCount: 61,
  },
  {
    id: 'v1',
    name: 'Nuwara Eliya Fresh Carrots',
    description: 'Crispy, sweet, premium carrots straight from the cold valley hills of Nuwara Eliya. High beta-carotene and completely direct-source.',
    category: 'veggies',
    price: 420,
    originalPrice: 480,
    discountPercent: 12,
    unit: '500g',
    image: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 30,
    rating: 4.7,
    reviewsCount: 104,
  },
  {
    id: 'v2',
    name: 'Organic Vine Ripe Red Tomatoes',
    description: 'Juicy, bright red vine tomatoes cultivated organically. Excellent for Sri Lankan curries, fresh salads, or traditional tomato sambol.',
    category: 'veggies',
    price: 380,
    unit: '500g',
    image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=500&auto=format&fit=crop&q=80',
    popular: false,
    stock: 45,
    rating: 4.5,
    reviewsCount: 79,
  },
  {
    id: 'v3',
    name: 'Fresh Green Broccoli Crown',
    description: 'Crisp green broccoli florets. Sourced directly from hill country greenhouse growers, rich in antioxidants.',
    category: 'veggies',
    price: 950,
    originalPrice: 1100,
    discountPercent: 13,
    unit: '350g',
    image: 'https://images.unsplash.com/photo-1452960962994-acf4fd70b632?w=500&auto=format&fit=crop&q=80',
    popular: false,
    stock: 15,
    rating: 4.4,
    reviewsCount: 35,
  },

  // Dairy & Eggs
  {
    id: 'd1',
    name: 'Kotmale Pure Sri Lankan Salted Butter',
    description: 'Premium quality golden butter crafted from pure cows milk sourced from up-country dairy farms in Sri Lanka. Rich and savory.',
    category: 'dairy',
    price: 980,
    unit: '200g block',
    image: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 19,
    rating: 4.9,
    reviewsCount: 215,
  },
  {
    id: 'd2',
    name: 'Fresh Farm White Eggs (10 Pack)',
    description: 'Guaranteed fresh, clean farm eggs. Sourced from high-standard sanitary poultry farms with veterinary approval.',
    category: 'dairy',
    price: 520,
    originalPrice: 580,
    discountPercent: 10,
    unit: '10 Pack',
    image: 'https://images.unsplash.com/photo-1516448620398-c5f44bf9f441?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 40,
    rating: 4.8,
    reviewsCount: 312,
  },
  {
    id: 'd3',
    name: 'Pelwatte Full Cream Liquid Milk',
    description: '100% natural, pasture-grazed fresh milk sterilized for long life. Absolutely no additives, preservatives or added sugars.',
    category: 'dairy',
    price: 490,
    unit: '1 L Tetrapack',
    image: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=500&auto=format&fit=crop&q=80',
    popular: false,
    stock: 55,
    rating: 4.7,
    reviewsCount: 164,
  },

  // Bakery & Bread
  {
    id: 'b1',
    name: 'Artisanal Sourdough Bread',
    description: 'Traditionally baked naturally-fermented sourdough bread. Featuring a blistered thick caramelized crust and soft, airy interior.',
    category: 'bakery',
    price: 850,
    unit: '600g loaf',
    image: 'https://images.unsplash.com/photo-1549931319-a545dcf3bc73?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 8,
    rating: 4.9,
    reviewsCount: 94,
  },
  {
    id: 'b2',
    name: 'Soft French Chocolate Croissants',
    description: 'Golden flaky pastries made with layers of buttery laminated dough and filled with decadent gourmet dark chocolate batons.',
    category: 'bakery',
    price: 680,
    originalPrice: 800,
    discountPercent: 15,
    unit: '2 Pack',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=500&auto=format&fit=crop&q=80',
    popular: false,
    stock: 14,
    rating: 4.6,
    reviewsCount: 57,
  },

  // Meat & Seafood
  {
    id: 'm1',
    name: 'Fresh Skinless Antibiotic-Free Chicken Breast',
    description: 'Premium choice double chicken outer breast portions. Sourced from high-welfare, cage-free poultry environments.',
    category: 'meats',
    price: 1350,
    originalPrice: 1600,
    discountPercent: 15,
    unit: '500g pack',
    image: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 16,
    rating: 4.8,
    reviewsCount: 183,
  },
  {
    id: 'm2',
    name: 'Wild Sri Lankan Yellowfin Tuna Steak',
    description: 'Sashimi-grade dark crimson local Yellowfin tuna fillets. Vacuum-sealed fresh within hours of deep ocean harvest.',
    category: 'meats',
    price: 2450,
    originalPrice: 2900,
    discountPercent: 15,
    unit: '500g',
    image: 'https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 10,
    rating: 4.9,
    reviewsCount: 74,
  },

  // Pantry & Staples
  {
    id: 'p1',
    name: 'Araliya Keeri Samba Premium Rice',
    description: 'Superior aromatic white rice, age-matured and polished to perfection. This local premium classic cooks fluffy and small-grained.',
    category: 'pantry',
    price: 1300,
    unit: '5 kg bag',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 35,
    rating: 4.9,
    reviewsCount: 420,
  },
  {
    id: 'p2',
    name: 'Organic Virgin Coconut Oil',
    description: '100% cold-pressed organic coconut oil extracted from the white kernel of Sri Lankan coconuts. Pure essence for raw cooking or wellness.',
    category: 'pantry',
    price: 1550,
    originalPrice: 1850,
    discountPercent: 16,
    unit: '500ml glass jar',
    image: 'https://images.unsplash.com/photo-1622484211148-717af99d45e5?w=500&auto=format&fit=crop&q=80',
    popular: false,
    stock: 22,
    rating: 4.7,
    reviewsCount: 103,
  },

  // Beverages
  {
    id: 'be1',
    name: 'Dilmah Premium English Breakfast Tea',
    description: 'Finest Ceylon single-origin tea, harvested from the rich, high-grown mountains of central Sri Lanka. Strong, full-bodied flavors.',
    category: 'beverages',
    price: 820,
    unit: '50 String Tea Bags',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 48,
    rating: 4.8,
    reviewsCount: 290,
  },
  {
    id: 'be2',
    name: 'Fresh King Coconut Water',
    description: '100% pure premium bottled Thambili (King Coconut) water. The ultimate natural isotonic hydrating drink of Sri Lanka.',
    category: 'beverages',
    price: 320,
    originalPrice: 380,
    discountPercent: 15,
    unit: '350ml bottle',
    image: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?w=500&auto=format&fit=crop&q=80',
    popular: false,
    stock: 30,
    rating: 4.9,
    reviewsCount: 112,
  },

  // Snacks & Sweets
  {
    id: 's1',
    name: 'Sri Lankan Classic Spicy Cashews',
    description: 'Crunchy premium Sri Lankan split cashews tossed with red chili pepper and fresh curry leaves. Extremely addictive local gourmet snack.',
    category: 'snacks',
    price: 1450,
    originalPrice: 1750,
    discountPercent: 17,
    unit: '200g stand pouch',
    image: 'https://images.unsplash.com/photo-1511125341079-05a909dd6802?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 20,
    rating: 4.9,
    reviewsCount: 150,
  },
  {
    id: 's2',
    name: 'Pure Kithul Jaggery Blocks',
    description: 'Traditional sweet syrup wood-hardened blocks extracted naturally from Colombo outer district Kithul palm flower trees.',
    category: 'snacks',
    price: 790,
    unit: '250g pack',
    image: 'https://images.unsplash.com/photo-1608686207856-001b95cf60ca?w=500&auto=format&fit=crop&q=80',
    popular: false,
    stock: 15,
    rating: 4.6,
    reviewsCount: 44,
  },
  {
    id: 'fr1',
    name: 'Premium Frozen French Fries',
    description: 'Crispy, premium quality frozen golden french fries. Quick to fry or bake, perfect side snack.',
    category: 'frozen',
    price: 890,
    originalPrice: 1100,
    discountPercent: 19,
    unit: '1 kg pack',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 22,
    rating: 4.7,
    reviewsCount: 55,
  },
  {
    id: 'fr2',
    name: 'Frozen Green Peas Premium pack',
    description: 'Gently steam-blanched and individually quick frozen (IQF) fresh sweet green peas. Locks in deep green richness and vitamins.',
    category: 'frozen',
    price: 650,
    unit: '500g bag',
    image: 'https://images.unsplash.com/photo-1587486913049-53fc88980cfc?w=500&auto=format&fit=crop&q=80',
    popular: false,
    stock: 18,
    rating: 4.5,
    reviewsCount: 31,
  },
  {
    id: 'cl1',
    name: 'Multipurpose Antibacterial Cleaning Spray',
    description: 'Kills 99.9% of bacteria and viruses on grease, dust and kitchen countertops. Fast lemon freshness clean.',
    category: 'cleaning',
    price: 750,
    originalPrice: 950,
    discountPercent: 21,
    unit: '500ml',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 30,
    rating: 4.8,
    reviewsCount: 120,
  },
  {
    id: 'cl2',
    name: 'Eco Dishwashing Liquid Gel',
    description: 'Natural coconut extracts cut deep through tough kitchen food oils. Completely soft and smooth on hands.',
    category: 'cleaning',
    price: 490,
    unit: '750ml bottle',
    image: 'https://images.unsplash.com/photo-1607006342460-7a97fd0229fa?w=500&auto=format&fit=crop&q=80',
    popular: false,
    stock: 45,
    rating: 4.6,
    reviewsCount: 84,
  },
  
  // 🔥 SECTION 1 & 3: TRENDING PRODUCTS
  {
    id: 't1_anchor',
    name: 'Anchor Full Cream Milk 1L',
    description: 'High-quality pastured full cream milk loaded with essential nutrients. Sourced from grass-fed Sri Lankan herds.',
    category: 'dairy',
    price: 380,
    originalPrice: 420,
    discountPercent: 10,
    unit: '1L Pack',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 25,
    rating: 4.8,
    reviewsCount: 310,
  },
  {
    id: 't1_delmege_basmati',
    name: 'Delmege Basmati Rice 5kg',
    description: 'Aromatic, fine, long-grain basmati rice. Twice aged for robust volume expand and flavor retention.',
    category: 'pantry',
    price: 1850,
    unit: '5kg pack',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 15,
    rating: 4.7,
    reviewsCount: 180,
  },
  {
    id: 't1_coke',
    name: 'Coca-Cola 1.5L',
    description: 'Sizzling, crisp-tasting soft beverage. Best served ice cold for sparkling fizzy refreshment.',
    category: 'beverages',
    price: 290,
    originalPrice: 320,
    discountPercent: 9,
    unit: '1.5L Bottle',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 50,
    rating: 4.6,
    reviewsCount: 654,
  },
  {
    id: 't1_maliban_crackers',
    name: 'Maliban Cream Crackers 200g',
    description: 'Crispy, premium bake salted square crackers. Perfectly pairs with milk tea or local cheddar cheese.',
    category: 'snacks',
    price: 175,
    unit: '200g pack',
    image: 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 45,
    rating: 4.5,
    reviewsCount: 220,
  },
  {
    id: 't1_sunlight',
    name: 'Sunlight Dishwash 750ml',
    description: 'Power of real lime slices cuts through raw kitchen oils. Completely safe and kind on palms.',
    category: 'cleaning',
    price: 320,
    originalPrice: 380,
    discountPercent: 16,
    unit: '750ml Bottle',
    image: 'https://images.unsplash.com/photo-1607006342460-7a97fd0229fa?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 30,
    rating: 4.7,
    reviewsCount: 145,
  },
  {
    id: 't1_parachute_oil',
    name: 'Parachute Coconut Oil 500ml',
    description: '100% natural, pure, cold-pressed double filtered edible coconut oil. Promotes glowing hair and health.',
    category: 'pantry',
    price: 680,
    unit: '500ml bottle',
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=500&auto=format&fit=crop&q=80',
    popular: false,
    stock: 20,
    rating: 4.8,
    reviewsCount: 92,
  },
  {
    id: 't1_munchee_puff',
    name: 'Munchee Chocolate Puff 150g',
    description: 'Crispy baked pastry cups filled with luscious, rich dark chocolate core cream loops.',
    category: 'snacks',
    price: 195,
    originalPrice: 220,
    discountPercent: 11,
    unit: '150g pack',
    image: 'https://images.unsplash.com/photo-1530610476181-d83430b64d00?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 25,
    rating: 4.6,
    reviewsCount: 115,
  },
  {
    id: 't1_surf_excel',
    name: 'Surf Excel Washing Powder 1kg',
    description: 'Supreme stain removal technology penetrates deep into micro fibers to remove heavy mud and spills instantly.',
    category: 'cleaning',
    price: 540,
    originalPrice: 600,
    discountPercent: 10,
    unit: '1kg pack',
    image: 'https://images.unsplash.com/photo-1551248429-40975aa4de74?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 18,
    rating: 4.7,
    reviewsCount: 88,
  },
  {
    id: 't1_delmege_juice',
    name: 'Delmege Orange Juice 1L',
    description: 'Squeezed from choice Mediterranean oranges. Packed with essential vitamin-c protection.',
    category: 'beverages',
    price: 350,
    unit: '1L Tetrapack',
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=500&auto=format&fit=crop&q=80',
    popular: false,
    stock: 35,
    rating: 4.5,
    reviewsCount: 76,
  },
  {
    id: 't1_araliya_basmati',
    name: 'Araliya Rose Basmati 1kg',
    description: 'Unique pinkish long range rose basmati. Highly sought after for weddings and festival rice dishes.',
    category: 'pantry',
    price: 490,
    unit: '1kg bag',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80',
    popular: false,
    stock: 40,
    rating: 4.4,
    reviewsCount: 33,
  },

  // 🌿 SECTION 2: FRESH PRODUCTS
  {
    id: 't2_carrots',
    name: 'Fresh Carrots 500g',
    description: 'Bright red, sweet fresh produce carrots direct from Colombo organic local crop markets.',
    category: 'veggies',
    price: 120,
    unit: '500g bag',
    image: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 30,
    rating: 4.8,
    reviewsCount: 160,
  },
  {
    id: 't2_tomatoes',
    name: 'Tomatoes 1kg',
    description: 'Hand-sorted ripe vine organic red tomatoes. Rich in vitamin A, perfect base for local sambol.',
    category: 'veggies',
    price: 180,
    originalPrice: 220,
    discountPercent: 18,
    unit: '1kg bag',
    image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 25,
    rating: 4.7,
    reviewsCount: 110,
  },
  {
    id: 't2_spinach',
    name: 'Spinach Bunch',
    description: 'Fresh leafy green spinach harvested this dawn. Preserved in chilled mist for absolute crunch.',
    category: 'veggies',
    price: 90,
    unit: '1 Bunch',
    image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=500&auto=format&fit=crop&q=80',
    popular: false,
    stock: 15,
    rating: 4.9,
    reviewsCount: 45,
  },
  {
    id: 't2_bananas',
    name: 'Bananas 6pcs',
    description: 'Sweet, energy rich ripened local bananas. Complete fiber source for a dynamic day.',
    category: 'fruits',
    price: 150,
    unit: '6 Pieces',
    image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 28,
    rating: 4.8,
    reviewsCount: 130,
  },
  {
    id: 't2_apples',
    name: 'Apples 4pcs',
    description: 'Imported crunchy royal gala apples. Sourced from orchards that guarantee no pesticide sprays.',
    category: 'fruits',
    price: 320,
    originalPrice: 380,
    discountPercent: 16,
    unit: '4 Pack',
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 20,
    rating: 4.6,
    reviewsCount: 89,
  },
  {
    id: 't2_chicken',
    name: 'Fresh Chicken 1kg',
    description: 'Whole cut local fresh farm chicken. Cleanly de-feathered and certified by national veterinary teams.',
    category: 'meats',
    price: 980,
    originalPrice: 1100,
    discountPercent: 11,
    unit: '1kg bag',
    image: 'https://images.unsplash.com/photo-1587593817642-59992d523677?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 14,
    rating: 4.9,
    reviewsCount: 204,
  },
  {
    id: 't2_eggs',
    name: 'Eggs 10pcs',
    description: 'Guaranteed macro food local brown shell eggs. Farm collected daily with strict biological reviews.',
    category: 'dairy',
    price: 420,
    unit: '10 Pack',
    image: 'https://images.unsplash.com/photo-1516448620398-c5f44bf9f441?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 35,
    rating: 4.8,
    reviewsCount: 312,
  },
  {
    id: 't2_yogurt',
    name: 'Yogurt 400g',
    description: 'Thick, creamy Sri Lankan dairy yogurt. Probiotic properties supporting stable stomach metabolism.',
    category: 'dairy',
    price: 280,
    originalPrice: 320,
    discountPercent: 13,
    unit: '400g Tub',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 40,
    rating: 4.7,
    reviewsCount: 175,
  },
  {
    id: 't2_bread',
    name: 'Fresh Bread Loaf',
    description: 'Soft sliced premium bakery bread baked fresh each midnight with real yeast kernels.',
    category: 'bakery',
    price: 190,
    unit: '450g Loaf',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=80',
    popular: false,
    stock: 12,
    rating: 4.5,
    reviewsCount: 65,
  },
  {
    id: 't2_cheese',
    name: 'Cheddar Cheese 200g',
    description: 'Aged golden cheddar cheese blocks. Rich, tangy taste that melts smoothly in any grilled snacks.',
    category: 'dairy',
    price: 650,
    originalPrice: 720,
    discountPercent: 10,
    unit: '200g pack',
    image: 'https://images.unsplash.com/photo-1486299267070-83823f5448dd?w=500&auto=format&fit=crop&q=80',
    popular: false,
    stock: 18,
    rating: 4.6,
    reviewsCount: 42,
  },

  // ⚡ SECTION 4: FLASH DEALS
  {
    id: 'fd_milo',
    name: '⚡ Milo 400g Tin',
    description: 'Active-go chocolate malt energy beverage. Complete with crucial proteins and essential minerals.',
    category: 'beverages',
    price: 890,
    originalPrice: 1490,
    discountPercent: 40,
    unit: '400g Tin',
    image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 15,
    rating: 4.9,
    reviewsCount: 520,
  },
  {
    id: 'fd_nestomalt',
    name: '⚡ Nestomalt 400g',
    description: 'Sri Lankas favorite golden power malt mix. Perfect daily tea-match energy boost.',
    category: 'beverages',
    price: 720,
    originalPrice: 1100,
    discountPercent: 35,
    unit: '400g Box',
    image: 'https://images.unsplash.com/photo-1595981267035-7b04ec4162d2?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 20,
    rating: 4.8,
    reviewsCount: 412,
  },
  {
    id: 'fd_cream_soda',
    name: '⚡ Elephant House Cream Soda 1.5L',
    description: 'Legendary sweet cream bubble carbonated soda. Loved by generations of Sri Lankan teens.',
    category: 'beverages',
    price: 185,
    originalPrice: 260,
    discountPercent: 29,
    unit: '1.5L Bottle',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 50,
    rating: 4.7,
    reviewsCount: 960,
  },
  {
    id: 'fd_kfc_chicken',
    name: '⚡ KFC Style Chicken 1kg',
    description: 'Pre-marinated hot & spicy southern recipe chicken wings and thighs. Ready to deep-fry.',
    category: 'meats',
    price: 750,
    originalPrice: 1200,
    discountPercent: 38,
    unit: '1kg bag',
    image: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 10,
    rating: 4.8,
    reviewsCount: 142,
  },
  {
    id: 'fd_delmege_pasta',
    name: '⚡ Delmege Pasta 400g',
    description: 'Premium durum wheat macaroni loops. High gluten chewiness, cooks perfectly in eight minutes.',
    category: 'pantry',
    price: 180,
    originalPrice: 300,
    discountPercent: 40,
    unit: '400g pack',
    image: 'https://images.unsplash.com/photo-1551462147-ff29053bfc14?w=500&auto=format&fit=crop&q=80',
    popular: false,
    stock: 25,
    rating: 4.6,
    reviewsCount: 77,
  },
  {
    id: 'fd_maggi_noodles',
    name: '⚡ Maggi Noodles 5pack',
    description: 'Instant local spice-match chicken noodles set. Quick comfort meal done in two minutes flat.',
    category: 'pantry',
    price: 290,
    originalPrice: 420,
    discountPercent: 31,
    unit: '5 Pack',
    image: 'https://images.unsplash.com/photo-1612966608997-30004f7c9e0d?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 35,
    rating: 4.8,
    reviewsCount: 228,
  },
  {
    id: 'fd_pringles',
    name: '⚡ Pringles Original 165g',
    description: 'Slices of crisp potatoes loaded in legendary vacuum canisters. Completely uniform crunch.',
    category: 'snacks',
    price: 490,
    originalPrice: 750,
    discountPercent: 35,
    unit: '165g tube',
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 24,
    rating: 4.7,
    reviewsCount: 165,
  },
  {
    id: 'fd_anchor_butter',
    name: '⚡ Anchor Butter 200g',
    description: 'Creamy New Zealand cattle pasture butter. Perfect addition to premium baked delicacies.',
    category: 'dairy',
    price: 580,
    originalPrice: 860,
    discountPercent: 33,
    unit: '200g block',
    image: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=500&auto=format&fit=crop&q=80',
    popular: true,
    stock: 15,
    rating: 4.9,
    reviewsCount: 198,
  },
  {
    id: 'fd_ovaltine',
    name: '⚡ Ovaltine 400g',
    description: 'Classic European milk malt chocolate drink powder. High calcium and essential vitamins.',
    category: 'beverages',
    price: 680,
    originalPrice: 980,
    discountPercent: 31,
    unit: '400g Box',
    image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=500&auto=format&fit=crop&q=80',
    popular: false,
    stock: 12,
    rating: 4.5,
    reviewsCount: 52,
  },
  {
    id: 'fd_harpic',
    name: '⚡ Harpic Toilet Cleaner',
    description: 'Advanced thick blue gel cuts through persistent lime and kills 99.9% of sanitation germs.',
    category: 'cleaning',
    price: 320,
    originalPrice: 520,
    discountPercent: 38,
    unit: '500ml',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=500&auto=format&fit=crop&q=80',
    popular: false,
    stock: 22,
    rating: 4.7,
    reviewsCount: 110,
  }
];

export const INITIAL_ADDRESSES: Address[] = [
  {
    id: 'a1',
    label: 'Home (Default)',
    details: 'Apt 4B, 24/1 Duplication Road, Colombo 03',
    isDefault: true,
  },
  {
    id: 'a2',
    label: 'Office',
    details: 'Level 14, World Trade Center East Tower, Colombo 01',
    isDefault: false,
  },
];

export const ADS_CAROUSEL = [
  {
    id: 'ad1',
    title: 'WEEKEND FRESH DEALS',
    subtitle: 'Up to 20% off pure Nuwara Eliya veggies',
    tag: 'LIMITED DEAL',
    bg: '#FFFBEA',
    textColor: '#1A1A1A',
    borderColor: '#F5C518',
  },
  {
    id: 'ad2',
    title: 'COLOMBO FLAT DELIVERIES',
    subtitle: 'LKR 0 delivery of fresh meats on orders > LKR 3,000',
    tag: 'ZIPPI EXCLUSIVE',
    bg: '#E8F0FE',
    textColor: '#1565C0',
    borderColor: '#1565C0',
  },
  {
    id: 'ad3',
    title: 'CURRY BASKET SPECIAl',
    subtitle: 'Keeri Samba, potatoes & coconuts 12% combo off',
    tag: 'POPULAR BUNDLE',
    bg: '#E8F5E9',
    textColor: '#2E7D32',
    borderColor: '#2E7D32',
  }
];
